# Images and labels direcotry should be relative to train.py
TRAIN_DIR_IMAGES: 'data/train-2'
TRAIN_DIR_LABELS: 'data/labels/train'
VALID_DIR_IMAGES: 'data/validate-2'
VALID_DIR_LABELS: 'data/labels/validate'
TEST_DIR_IMAGES: 'data/test-2'
TEST_DIR_LABELS: 'data/labels/test'

# Class names.
CLASSES: [
    '__background__',
    '2', '3', '4'
]

# Number of classes (object classes + 1 for background class in Faster RCNN).
NC: 4

# Whether to save the predictions of the validation set while training.
SAVE_VALID_PREDICTION_IMAGES: True
